services:
  - type: web
    name: fraud-detection-app
    env: python
    buildCommand: pip install -r req.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
